image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - front-end/node_modules/

# build_front_end:
#   stage: build
#   script:
#     - cd front-end
#     - npm install
#     - CI=false npm run-script build

test_selenium:
  stage: test
  services:
    - selenium/standalone-chrome
  image: python:3.9-slim
  before_script:
    - python3 -m pip install -r front-end/selenium/requirements.txt
  script:
    - python3 -m pytest

# deploy_develop: ??? https://github.com/forbesye/cs373/blob/main/Flask_AWS_Deploy.md

deploy_production:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - chmod +x ./.eb-config.sh
    - ./.eb-config.sh
    - git checkout main
  script:
    - cd back-end
    - /root/.local/bin/eb deploy adoptapet-api-prod
