image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - front-end/node_modules/

test_jest:
  stage: test
  image:
    name: mcgenius/pp_mocha
    entrypoint: [""]
  script:
    - cd front-end
    - npm install
    - npm test

