image: node:latest

stages:
  - build

cache:
  paths:
    - front-end/node_modules/

build_front_end:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build
